export const visibleLayers = [
  "climate:tmin",
  "climate:tmax",
  "climate:tmin_alaska",
  "climate:tmax_alaska",
  "climate:prism_ppt",
  "precipitation:buffelgrass_prism",
  "gdd:agdd_alaska",
  "gdd:agdd_alaska_50f",
  "gdd:agdd",
  "gdd:gdd:agdd_50f",
  "gdd:gdd:agdd_50f",
  "gdd:30yr_avg_agdd",
  "gdd:30yr_avg_agdd_50f",
  "gdd:agdd_anomaly",
  "gdd:agdd_anomaly_50f",
  "si-x:average_leaf_best",
  "si-x:average_bloom_best",
  "si-x:arnoldred_leaf_ncep_historic", //2016-Previous Year
  "si-x:arnoldred_bloom_ncep_historic",
  "si-x:lilac_leaf_ncep_historic",
  "si-x:lilac_bloom_ncep_historic",
  "si-x:zabelli_leaf_ncep_historic",
  "si-x:zabelli_bloom_ncep_historic",
  "si-x:average_leaf_ncep_historic",
  "si-x:average_bloom_ncep_historic",
  "si-x:arnoldred_leaf_ncep_alaska_historic", //2017-Previous Year
  "si-x:arnoldred_bloom_ncep_alaska_historic",
  "si-x:lilac_leaf_ncep_alaska_historic",
  "si-x:lilac_bloom_ncep_alaska_historic",
  "si-x:zabelli_leaf_ncep_alaska_historic",
  "si-x:zabelli_bloom_ncep_alaska_historic",
  "si-x:average_leaf_ncep_alaska_historic",
  "si-x:average_bloom_ncep_alaska_historic",
  "si-x:leaf_anomaly_historic",
  "si-x:bloom_anomaly_historic",
  "si-x:30yr_avg_4k_leaf", //4k
  "si-x:30yr_avg_4k_bloom",
  "si-x:30yr_avg_six_leaf", //2.5k
  "si-x:30yr_avg_six_bloom",
  "si-x:arnoldred_leaf_ncep", //current year
  "si-x:arnoldred_bloom_ncep",
  "si-x:lilac_leaf_ncep",
  "si-x:lilac_bloom_ncep",
  "si-x:zabelli_leaf_ncep",
  "si-x:zabelli_bloom_ncep",
  "si-x:average_leaf_ncep",
  "si-x:average_bloom_ncep",
  "si-x:arnoldred_leaf_ncep_alaska", //current year alaska
  "si-x:arnoldred_bloom_ncep_alaska",
  "si-x:lilac_leaf_ncep_alaska",
  "si-x:lilac_bloom_ncep_alaska",
  "si-x:zabelli_leaf_ncep_alaska",
  "si-x:zabelli_bloom_ncep_alaska",
  "si-x:average_leaf_ncep_alaska",
  "si-x:average_bloom_ncep_alaska",
  "si-x:leaf_anomaly", //daily anomaly current year
  "si-x:bloom_anomaly",
  "si-x:leaf_return_interval",
  "si-x:bloom_return_interval",
  "si-x:arnoldred_leaf_prism", // historic annual 1981 - previous year
  "si-x:arnoldred_bloom_prism",
  "si-x:lilac_leaf_prism",
  "si-x:lilac_bloom_prism",
  "si-x:zabelli_leaf_prism",
  "si-x:zabelli_bloom_prism",
  "si-x:average_leaf_prism",
  "si-x:average_bloom_prism",
  "si-x:leaf_anomaly_prism",
  "si-x:bloom_anomaly_prism",
  "inca:midgdown_median_nad83_02deg",
  "inca:midgup_median_nad83_02deg",
  "inca:eviarea_median_nad83_02deg",
  "inca:midgdown_mad_nad83_02deg",
  "inca:midgup_mad_nad83_02deg",
  "inca:eviarea_mad_nad83_02deg",
  "inca:midgdown_tsslope_nad83_02deg",
  "inca:midgup_tsslope_nad83_02deg",
  "inca:eviarea_tsslope_nad83_02deg",
  "caps:Avg_PEMa0_20201231",
  "caps:Avg_PEMa0Excl1_20201231",
  "caps:Avg_PEMa0Excl2_20201231"
];
